name: CI devops 2022 CPE 
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: 
      - master
  pull_request:

jobs: 
  test-backend:
    runs-on: ubuntu-18.04 
    steps:
      - uses: actions/checkout@v2.3.3   #checkout your github code using actions/checkout@v2.3.3
     
      - name: Set up JDK 11 #do the same with another action (actions/setup-java@v2) that enable to setup jdk 11
        uses: actions/setup-java@v2
        with:
          - distribution: "temurin"
          - java-version: "11"
          
      - name: Build and test with Maven #finally build your app with the latest command
        run: mvn clean verify --file ./Java/part2/simple-api/simple-api/pom.xml